// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: CfgVersion.proto

package dataConfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// key:["Id"]
type CfgVersion struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	BigVersion           int32    `protobuf:"varint,2,opt,name=BigVersion,proto3" json:"BigVersion,omitempty"`
	SmallVersion         int32    `protobuf:"varint,3,opt,name=SmallVersion,proto3" json:"SmallVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CfgVersion) Reset()         { *m = CfgVersion{} }
func (m *CfgVersion) String() string { return proto.CompactTextString(m) }
func (*CfgVersion) ProtoMessage()    {}
func (*CfgVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_CfgVersion_2ec47241c1875718, []int{0}
}
func (m *CfgVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CfgVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CfgVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CfgVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgVersion.Merge(dst, src)
}
func (m *CfgVersion) XXX_Size() int {
	return m.Size()
}
func (m *CfgVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgVersion.DiscardUnknown(m)
}

var xxx_messageInfo_CfgVersion proto.InternalMessageInfo

func (m *CfgVersion) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CfgVersion) GetBigVersion() int32 {
	if m != nil {
		return m.BigVersion
	}
	return 0
}

func (m *CfgVersion) GetSmallVersion() int32 {
	if m != nil {
		return m.SmallVersion
	}
	return 0
}

type VersionConfigData struct {
	Config               []*CfgVersion `protobuf:"bytes,1,rep,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VersionConfigData) Reset()         { *m = VersionConfigData{} }
func (m *VersionConfigData) String() string { return proto.CompactTextString(m) }
func (*VersionConfigData) ProtoMessage()    {}
func (*VersionConfigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_CfgVersion_2ec47241c1875718, []int{1}
}
func (m *VersionConfigData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VersionConfigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VersionConfigData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *VersionConfigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionConfigData.Merge(dst, src)
}
func (m *VersionConfigData) XXX_Size() int {
	return m.Size()
}
func (m *VersionConfigData) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionConfigData.DiscardUnknown(m)
}

var xxx_messageInfo_VersionConfigData proto.InternalMessageInfo

func (m *VersionConfigData) GetConfig() []*CfgVersion {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*CfgVersion)(nil), "dataConfig.CfgVersion")
	proto.RegisterType((*VersionConfigData)(nil), "dataConfig.VersionConfigData")
}
func (m *CfgVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CfgVersion) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCfgVersion(dAtA, i, uint64(m.Id))
	}
	if m.BigVersion != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintCfgVersion(dAtA, i, uint64(m.BigVersion))
	}
	if m.SmallVersion != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintCfgVersion(dAtA, i, uint64(m.SmallVersion))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *VersionConfigData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionConfigData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Config) > 0 {
		for _, msg := range m.Config {
			dAtA[i] = 0xa
			i++
			i = encodeVarintCfgVersion(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintCfgVersion(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CfgVersion) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCfgVersion(uint64(m.Id))
	}
	if m.BigVersion != 0 {
		n += 1 + sovCfgVersion(uint64(m.BigVersion))
	}
	if m.SmallVersion != 0 {
		n += 1 + sovCfgVersion(uint64(m.SmallVersion))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *VersionConfigData) Size() (n int) {
	var l int
	_ = l
	if len(m.Config) > 0 {
		for _, e := range m.Config {
			l = e.Size()
			n += 1 + l + sovCfgVersion(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCfgVersion(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCfgVersion(x uint64) (n int) {
	return sovCfgVersion(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CfgVersion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCfgVersion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CfgVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CfgVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCfgVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BigVersion", wireType)
			}
			m.BigVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCfgVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BigVersion |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SmallVersion", wireType)
			}
			m.SmallVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCfgVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SmallVersion |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCfgVersion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCfgVersion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VersionConfigData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCfgVersion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionConfigData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionConfigData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCfgVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCfgVersion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Config = append(m.Config, &CfgVersion{})
			if err := m.Config[len(m.Config)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCfgVersion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCfgVersion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCfgVersion(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCfgVersion
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCfgVersion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCfgVersion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCfgVersion
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCfgVersion
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCfgVersion(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCfgVersion = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCfgVersion   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("CfgVersion.proto", fileDescriptor_CfgVersion_2ec47241c1875718) }

var fileDescriptor_CfgVersion_2ec47241c1875718 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x70, 0x4e, 0x4b, 0x0f,
	0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x49,
	0x2c, 0x49, 0x74, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x57, 0x4a, 0xe0, 0xe2, 0x42, 0xc8, 0x0b, 0xf1,
	0x71, 0x31, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x79, 0xa6, 0x08, 0xc9,
	0x71, 0x71, 0x39, 0x65, 0xc2, 0x64, 0x25, 0x98, 0xc0, 0xe2, 0x48, 0x22, 0x42, 0x4a, 0x5c, 0x3c,
	0xc1, 0xb9, 0x89, 0x39, 0x39, 0x30, 0x15, 0xcc, 0x60, 0x15, 0x28, 0x62, 0x4a, 0xce, 0x5c, 0x82,
	0x50, 0x26, 0xc4, 0x4a, 0x97, 0xc4, 0x92, 0x44, 0x21, 0x3d, 0x2e, 0xb6, 0x64, 0x30, 0x4f, 0x82,
	0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x4c, 0x0f, 0xe1, 0x26, 0x3d, 0x84, 0x83, 0x82, 0xa0, 0xaa,
	0x9c, 0x04, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x19,
	0x8f, 0xe5, 0x18, 0x92, 0xd8, 0xc0, 0x7e, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x35,
	0x90, 0x89, 0xdf, 0x00, 0x00, 0x00,
}
